export const ADICIONA_PROJETO = "ADICIONA_PROJETO";
export const ALTERA_PROJETO = "ALTERA_PROJETO";
export const EXLUIR_PROJETO = "EXLUIR_PROJETO";

export const ADICIONA_TAREFA = "ADICIONA_TAREFA";
export const ALTERA_TAREFA = "ALTERA_TAREFA";
export const EXLUIR_TAREFA = "EXLUIR_TAREFA";